http_address="0.0.0.0:8000"
read_timeout="3s"
write_timeout="3s"
dbfile="app.db"

page_logo_url="/static/app/img/icon.png"
page_title="LinkPage"
page_intro="Your friendly neighbourhood self-hostable FOSS link page."

static_files = "static/custom"

[auth]
username="username"
password="password"

[social]
facebook = ""
instagram = ""
linkedin = ""
twitter = ""
youtube = ""
